# === Exact transforms generated by finite closed adjoint actions ===

function hermitian_generator_or_throw(G::QAdd)
    iszero(simplify(G - adjoint(G))) || unitary_error(
        "`UnitaryTransform(G, θ)` requires `G` to be provably Hermitian exactly",
    )
    return G
end

function phase_space_site_basis(operators::Vector{Op})
    position_index = findfirst(is_position, operators)
    momentum_index = findfirst(is_momentum, operators)
    position_index === nothing && unitary_error(
        "`UnitaryTransform(G, θ)` cannot infer a missing position rule for a phase-space " *
            "site; include both canonical quadratures in the generator",
    )
    momentum_index === nothing && unitary_error(
        "`UnitaryTransform(G, θ)` cannot infer a missing momentum rule for a phase-space " *
            "site; include both canonical quadratures in the generator",
    )
    return Op[operators[position_index], operators[momentum_index]]
end

function closed_adjoint_basis(G::QAdd)
    isempty(G.indices) || unitary_error(
        "`UnitaryTransform(G, θ)` does not yet support summed generators",
    )

    by_site = Dict{SiteKey, Vector{Op}}()
    for (term, _) in G
        isempty(term.ne) || unitary_error(
            "`UnitaryTransform(G, θ)` does not support constrained generator terms",
        )
        for operator in term.ops
            (has_index(operator.index) && index_slot(operator.index) === nothing) &&
                unitary_error(
                "`UnitaryTransform(G, θ)` does not yet support free indexed families",
            )
            push!(get!(by_site, site_key(operator), Op[]), operator)
        end
    end
    isempty(by_site) && unitary_error(
        "a scalar generator has a trivial adjoint action and no transformed operator basis",
    )

    raw = Op[]
    for operators in values(by_site)
        first_operator = first(operators)
        local_basis = if is_phase_space(first_operator)
            phase_space_site_basis(operators)
        else
            site_generators(first_operator)
        end
        isempty(local_basis) && unitary_error(
            "no finite exact generator basis is registered for `$first_operator`",
        )
        append!(raw, local_basis)
    end

    if all(is_fock, raw)
        lowerings = sort!(unique(lowering.(raw)))
        return vcat(lowerings, adjoint.(lowerings))
    elseif all(is_phase_space, raw)
        positions = sort!(Op[operator for operator in raw if is_position(operator)])
        momenta = Op[]
        for position in positions
            found = findfirst(
                operator -> is_momentum(operator) &&
                    site_key(operator) == site_key(position), raw,
            )
            found === nothing && unitary_error(
                "closed-adjoint basis lost the momentum paired with `$position`",
            )
            push!(momenta, raw[found])
        end
        return vcat(positions, momenta)
    end

    sort!(raw)
    unique!(raw)
    return raw
end

function affine_commutator_data(G::QAdd, basis::Vector{Op})
    n = length(basis)
    locations = Dict{Op, Int}(operator => i for (i, operator) in enumerate(basis))
    linear = fill(CNUM_ZERO, n, n)
    shift = fill(CNUM_ZERO, n)

    for (row, generator) in enumerate(basis)
        image = simplify(commutator(G, generator))
        isempty(image.indices) || unitary_error(
            "the adjoint action on `$generator` produced a summed expression",
        )
        for (term, coefficient) in image
            isempty(term.ne) || unitary_error(
                "the adjoint action on `$generator` produced constrained terms",
            )
            if isempty(term.ops)
                shift[row] = add_cnum(shift[row], coefficient)
            elseif length(term.ops) == 1
                target = first(term.ops)
                column = get(locations, target, 0)
                column == 0 && unitary_error(
                    "the adjoint action leaves the finite generator basis: " *
                        "`[$G, $generator]` contains `$target`",
                )
                linear[row, column] = add_cnum(linear[row, column], coefficient)
            else
                unsupported = rule_qadd((coefficient, copy(term.ops)))
                unitary_error(
                    "the adjoint action on `$generator` is not affine-linear; got " *
                        "`$(sprint(show, unsupported))`",
                )
            end
        end
    end
    return linear, shift
end

coefficient_is_real(c::CNum) = isequal(c, conj_cnum(c))
coefficient_is_zero(c::CNum) = iszero_cnum(c)

function coefficient_equal(left::CNum, right::CNum)
    return iszero_cnum(add_cnum(left, neg_cnum(right)))
end

function exact_real_argument(rate::CNum, θ::Real)
    coefficient_equal(rate, CNUM_ONE) && return θ
    coefficient_equal(rate, CNUM_NEG1) && return -θ
    return real(to_num(rate)) * θ
end

function generated_scalar_exponential(flow::CNum, θ::Real)
    coefficient_is_zero(flow) && return CNUM_ONE
    if coefficient_is_real(flow)
        coefficient_equal(flow, CNUM_ONE) && return to_cnum(exp(θ))
        coefficient_equal(flow, CNUM_NEG1) && return to_cnum(inv(exp(θ)))
        return to_cnum(exp(exact_real_argument(flow, θ)))
    end

    phase_rate = mul_cnum(CNUM_NEG_IM, flow)
    if coefficient_is_real(phase_rate)
        return phase(exact_real_argument(phase_rate, θ))
    end

    unitary_error(
        "no exact scalar exponential strategy supports the adjoint rate `$(to_num(flow))`",
    )
end

function connected_components(linear::Matrix{CNum})
    n = size(linear, 1)
    visited = falses(n)
    components = Vector{Vector{Int}}()
    for start in 1:n
        visited[start] && continue
        stack = Int[start]
        component = Int[]
        visited[start] = true
        while !isempty(stack)
            current = pop!(stack)
            push!(component, current)
            for other in 1:n
                other == current && continue
                connected = !coefficient_is_zero(linear[current, other]) ||
                    !coefficient_is_zero(linear[other, current])
                connected || continue
                visited[other] && continue
                visited[other] = true
                push!(stack, other)
            end
        end
        sort!(component)
        push!(components, component)
    end
    return components
end

function exact_rotation_pair(rate::CNum, θ::Real)
    if coefficient_equal(rate, CNUM_ONE)
        return to_cnum(cos(θ)), to_cnum(sin(θ))
    elseif coefficient_equal(rate, CNUM_NEG1)
        return to_cnum(cos(θ)), neg_cnum(to_cnum(sin(θ)))
    end
    angle = exact_real_argument(rate, θ)
    return to_cnum(cos(angle)), to_cnum(sin(angle))
end

function exact_two_by_two_flow!(
        result::Matrix{CNum}, flow::Matrix{CNum}, i::Int, j::Int, θ::Real,
    )
    coefficient_is_zero(flow[i, i]) && coefficient_is_zero(flow[j, j]) ||
        unitary_error(
        "exact two-dimensional adjoint blocks currently require zero diagonal entries",
    )
    upper = flow[i, j]
    lower = flow[j, i]

    if coefficient_is_real(upper) && coefficient_is_real(lower) &&
            coefficient_equal(lower, neg_cnum(upper))
        cosine, sine = exact_rotation_pair(upper, θ)
        result[i, i] = cosine
        result[i, j] = sine
        result[j, i] = neg_cnum(sine)
        result[j, j] = cosine
        return nothing
    end

    if coefficient_equal(lower, conj_cnum(upper))
        norm_squared = mul_cnum(upper, lower)
        if coefficient_equal(norm_squared, CNUM_ONE)
            ch = to_cnum(cosh(θ))
            sh = to_cnum(sinh(θ))
            result[i, i] = ch
            result[i, j] = mul_cnum(upper, sh)
            result[j, i] = mul_cnum(lower, sh)
            result[j, j] = ch
            return nothing
        elseif coefficient_is_real(upper) && coefficient_equal(lower, upper)
            angle = exact_real_argument(upper, θ)
            ch = to_cnum(cosh(angle))
            sh = to_cnum(sinh(angle))
            result[i, i] = ch
            result[i, j] = sh
            result[j, i] = sh
            result[j, j] = ch
            return nothing
        end
    end

    unitary_error(
        "no exact two-dimensional exponential strategy supports the closed adjoint block " *
            "[$(to_num(upper)), $(to_num(lower))]",
    )
end

function exact_closed_adjoint_action(
        basis::Vector{Op}, linear::Matrix{CNum}, shift::Vector{CNum}, θ::Real,
    )
    n = length(basis)
    flow = Matrix{CNum}(undef, n, n)
    affine_flow = Vector{CNum}(undef, n)
    for j in 1:n, i in 1:n
        flow[i, j] = mul_cnum(CNUM_IM, linear[i, j])
    end
    for i in 1:n
        affine_flow[i] = mul_cnum(CNUM_IM, shift[i])
    end

    has_linear = any(value -> !coefficient_is_zero(value), flow)
    has_shift = any(value -> !coefficient_is_zero(value), affine_flow)
    if has_shift
        has_linear && unitary_error(
            "closed affine adjoint actions with simultaneous linear and translation parts " *
                "do not yet have an exact exponential strategy",
        )
        parameter = to_cnum(θ)
        offsets = CNum[mul_cnum(parameter, value) for value in affine_flow]
        identity = fill(CNUM_ZERO, n, n)
        for i in 1:n
            identity[i, i] = CNUM_ONE
        end
        return AffineAction(basis, identity, offsets)
    end

    result = fill(CNUM_ZERO, n, n)
    for component in connected_components(flow)
        if length(component) == 1
            i = only(component)
            result[i, i] = generated_scalar_exponential(flow[i, i], θ)
        elseif length(component) == 2
            exact_two_by_two_flow!(result, flow, component[1], component[2], θ)
        else
            unitary_error(
                "the adjoint action closes on a $(length(component))-dimensional coupled " *
                    "block, but no exact exponential strategy is registered for it",
            )
        end
    end
    return AffineAction(basis, result, fill(CNUM_ZERO, n))
end

"""
    UnitaryTransform(G, θ)

Construct the exact adjoint action of `exp(-im*θ*G)` when the commutator with a finite
complete generator basis closes affinely and every resulting block has a registered exact
exponential strategy. Unsupported closed blocks are refused; there is no numerical fallback.
"""
function UnitaryTransform(G::QAdd, θ::Real)
    hermitian_generator_or_throw(G)
    basis = closed_adjoint_basis(G)
    linear, shift = affine_commutator_data(G, basis)
    return canonical_transform(exact_closed_adjoint_action(basis, linear, shift, θ))
end

UnitaryTransform(G::QSym, θ::Real) =
    UnitaryTransform(single_qadd(CNUM_ONE, Op[G]), θ)

"""
    RotatingFrame(H0, t)

Construct the exact moving frame `exp(-im*t*H0)` for a supported time-independent
Hermitian generator. The frame carries gauge `-H0`.
"""
function RotatingFrame(H0::QAdd, t::Num)
    tt = time_or_throw(t)
    variable = SymbolicUtils.unwrap(tt)
    for (_, coefficient) in H0
        coefficient_depends_on(coefficient, variable) && unitary_error(
            "`RotatingFrame(H0, t)` requires a time-independent `H0`",
        )
    end
    U = UnitaryTransform(H0, tt)
    return timed_transform(U, -H0, tt)
end

RotatingFrame(H0::QSym, t::Num) =
    RotatingFrame(single_qadd(CNUM_ONE, Op[H0]), t)
