name: IntegrationTest
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Downstream.yml'
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/Downstream.yml'
      - 'src/**'
      - 'ext/**'
      - 'test/**'
      - 'Project.toml'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch:

jobs:
  test:
    name: QuantumCumulants.jl/${{ matrix.julia-version }}
    runs-on: ${{ matrix.os }}
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - name: Clone QuantumCumulants migration branch
        uses: actions/checkout@v7
        with:
          repository: qojulia/QuantumCumulants.jl
          ref: compat/sqa-0.12
          path: downstream
      - name: Load this and run the downstream tests
        shell: julia --color=yes --project=@. --depwarn=yes {0}
        run: |
          using Pkg
          using TOML

          sqa_version = VersionNumber(TOML.parsefile("Project.toml")["version"])
          sqa_compat = "=" * string(sqa_version)

          function pin_sqa_compat(project_file, compat_spec)
            isfile(project_file) || return
            project = TOML.parsefile(project_file)
            compat = get(project, "compat", nothing)
            compat isa AbstractDict || return
            previous = get(compat, "SecondQuantizedAlgebra", nothing)
            previous === nothing && return
            compat["SecondQuantizedAlgebra"] = compat_spec
            open(project_file, "w") do io
              TOML.print(io, project)
            end
          end

          pin_sqa_compat(joinpath("downstream", "Project.toml"), sqa_compat)
          pin_sqa_compat(joinpath("downstream", "test", "Project.toml"), sqa_compat)

          Pkg.activate("downstream")
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.update()
          Pkg.test(coverage=true)
